name: CI-Polaris-Basic-Angular
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.9.0
        with:
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_name: "Renfe Testing"
          polaris_project_name: "Renfe Java Demo"
      - name: Extract Test IDs
        id: extract-ids
        run: |
          SAST_ID=$(grep 'Results for test "SAST" with id' .bridge/bridge.log | awk -F'id "' '{print $2}' | awk -F'"' '{print $1}')
          SCA_ID=$(grep 'Results for test "SCA" with id' .bridge/bridge.log | awk -F'id "' '{print $2}' | awk -F'"' '{print $1}')
          echo "SAST_ID=${SAST_ID}" >> $GITHUB_ENV
          echo "SCA_ID=${SCA_ID}" >> $GITHUB_ENV
      - name: Print Extracted Test IDs
        run: |
          echo "SAST Test ID: $SAST_ID"
          echo "SCA Test ID: $SCA_ID"
